# http://travis-ci.org/#!/jupyter-widgets/ipywidgets
language: python
dist: xenial
os: linux
arch:
  - amd64
python:
    - 3.8
addons:
  firefox: latest
services:
  - xvfb
cache: yarn
sudo: false
before_install:
    - 'nvm install 12'
install:
    - 'bash ./scripts/travis_install_js.sh'
script:
    - 'bash ./scripts/travis_script_js.sh'
