# http://travis-ci.org/#!/ipython/ipywidgets
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
env:
    - GROUP=python
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - pip install -f travis-wheels/wheelhouse file://$PWD#egg=ipywidgets[test] coveralls
script:
    - export IPYWIDGETS_PATH=$(python -c "import ipywidgets; print(ipywidgets.__path__)[0]")
    - 'if [[ $GROUP == js ]]; then cd $IPYWIDGETS_PATH && npm install && npm run test:$BROWSER; fi'
    - 'if [[ $GROUP == python ]]; then mkdir /tmp/ipywidgets && cd /tmp/ipywidgets && nosetests --with-coverage --cover-package=ipywidgets ipywidgets; fi'
matrix:
    include:
        - python: 2.7
          env: GROUP=js; BROWSER=firefox
        - python: 2.7
          env: GROUP=js; BROWSER=chrome
after_success:
    - coveralls
