name: ipywidget_docs
channels:
- conda-forge
- defaults
dependencies:
- ipykernel
- jinja2
- jupyter_sphinx
- nbformat
- nbsphinx
- notebook>=4.2
- python=3.6
- sphinx>=1.4.6
- sphinx_rtd_theme
- tornado
- recommonmark
- python-dateutil
- pip:
  - ipywidgets >=7.1.0rc1
  - jupyter-alabaster-theme
