name: ipywidget_docs
channels:
- conda-forge
- defaults
dependencies:
- python=3
- sphinx
- jinja2
- tornado
- nbformat
- ipywidgets
- notebook
- ipykernel
- nbsphinx
- jupyter_sphinx
- python-dateutil
- pip:
  - jupyter-alabaster-theme
  - docutils<0.13.1
  - recommonmark
