name: Test Spec

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}-${{hashFiles('**/requirements.txt')}}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install file://$PWD#egg=ipywidgets[test] coveralls
    - name: Test spec
      run: |
        python ./packages/schema/generate-spec.py > spec.md
        diff -u ./packages/schema/jupyterwidgetmodels.latest.md ./spec.md
